db:
  db: "./planet.sqlite"
  migration_dir: "./db/migrations"
hb:
  timezone: "Asia/Tokyo"
  template_dir: "./template"
  url: "https://www.eniehack.net/~eniehack/planet"
  meta:
    title: "planet eniehack"
    description: ""
picker:
  sites:
    - id: scrapbox
      type: scrapbox
      params:
        source_url: 
        site_url: https://scrapbox.io/eniehack/
        name: 
        icon_url: 