db:
  db: "./planet.sqlite"
  migration_dir: "./db/migrations"
hb:
  timezone: "Asia/Tokyo"
  template_dir: "./template"
  meta:
    url: "https://www.eniehack.net/~eniehack/planet"
    title: "planet eniehack"
    description: ""